### ISSUE TITLE
Pull Request Template Not Working?

### ISSUE THREAD

**Issue by Umayarz18** [Bhuvnesh875/S.D.E.#19]
### Description

After submitting my typo PR, I noticed it did not prompt me to use the PR template in the `.github` folder. I know the template exists inside another folder like how the [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) says you can have it. So I find it weird it does not work.

When I look at the insights of this repo  and under the community standards checklist, it also says there are no pull request templates. So I'm guessing something is up with Github docs on PR templates or I must have done something weird when I submitted a PR.

### Screenshots

![image](https://user-images.githubusercontent.com/61628982/155813757-fe8216d9-5dce-4859-b911-b24507e60d29.png)

**Comment by Bhuvnesh875** [comment]
thanks for opening the issue! Fixed it.
